#!/usr/bin/env bash
# setup-local.sh — makes WorldWideView turnkey for `docker compose` on any Docker host.
# Idempotent & safe to re-run. Prepares: .env (with real secrets), the data-engine
# seeders (so the globe shows live data), and the plugins-local mount dir.
#
# Usage:
#   ./setup-local.sh
#   docker compose --profile engine up --build
set -euo pipefail
cd "$(dirname "$0")"
ROOT="$(pwd)"
echo "==> WorldWideView local setup in: $ROOT"

# 1) .env with REAL secrets (only generated if absent; existing .env is left untouched)
if [ ! -f .env ]; then
  echo "==> generating .env (local edition, fresh secrets)"
  cat > .env <<EOF
# --- WorldWideView local config (generated by setup-local.sh) ---
NEXT_PUBLIC_WWV_EDITION=local

# REQUIRED boot gates — src/instrumentation.ts throws at startup without these:
AUTH_SECRET=$(openssl rand -hex 32)
ENCRYPTION_MASTER_KEY=$(openssl rand -hex 32)
API_KEY_HMAC_SECRET=$(openssl rand -hex 32)

# Local data engine. The browser actually connects via a hardcoded localhost:5000;
# this var is only the cloud fallback for plugins the local engine doesn't serve.
NEXT_PUBLIC_WWV_PLUGIN_DATA_ENGINE_URL=ws://localhost:5000
PROXY_HOST_ALLOWLIST=*

# OPTIONAL imagery — base globe renders WITHOUT any of these (keyless Google XYZ ->
# Cesium Ion default -> OpenStreetMap fallback chain). Set a Cesium Ion token for
# reliable base imagery, and a Google key for Photorealistic 3D Tiles:
NEXT_PUBLIC_CESIUM_ION_TOKEN=
NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=
NEXT_PUBLIC_BING_MAPS_KEY=

# OPTIONAL seeder keys — most of the 14 seeders are keyless; these two self-skip if blank:
OTX_API_KEY=
AISSTREAM_API_KEY=
EOF
else
  echo "==> .env already present — leaving it as-is"
fi

# 2) plugins-local mount dir (compose mounts it read-only; avoids an empty-mount surprise)
mkdir -p public/plugins-local && touch public/plugins-local/.gitkeep

# 3) data-engine seeders — the engine mounts ./local-seeders:/app/seeders and loads
#    community/<seeder>/dist/index.mjs. Stage the prebuilt published bundles (SDK inlined).
if [ -f local-seeders/community/earthquakes/dist/index.mjs ]; then
  echo "==> seeders already staged ($(ls -d local-seeders/community/*/ 2>/dev/null | grep -cv node_modules) packages)"
else
  echo "==> staging data-engine seeders from the published release zip..."
  mkdir -p local-seeders/community
  tmp="$(mktemp -d)"
  curl -fsSL https://github.com/silvertakana/wwv-seeders/releases/latest/download/seeders.zip -o "$tmp/seeders.zip"
  if command -v unzip >/dev/null 2>&1; then
    unzip -q -o "$tmp/seeders.zip" -d local-seeders/community
  else
    python3 -c "import zipfile; zipfile.ZipFile('$tmp/seeders.zip').extractall('local-seeders/community')"
  fi
  rm -rf "$tmp"
  # workspace root files (compose runs `cd community && CI=true pnpm install` here)
  printf '{\n  "name": "wwv-seeders-community",\n  "version": "1.0.0",\n  "private": true\n}\n' > local-seeders/community/package.json
  printf 'packages:\n  - "*"\n' > local-seeders/community/pnpm-workspace.yaml
  cat > local-seeders/community/.npmrc <<'NPMRC'
# Hoist deps flat so the prebuilt seeder dist bundles resolve bare imports
# (better-sqlite3, ioredis, geoip-lite, ...) via Node's upward directory walk.
node-linker=hoisted
shamefully-hoist=true
frozen-lockfile=false
NPMRC
  echo "==> staged $(ls -d local-seeders/community/*/ 2>/dev/null | grep -cv node_modules) seeder packages"
fi

# 4) Older docker compose only: pre-create the (unused) external 'coolify' network so
#    `up` can't abort on it. Modern compose (v2.20+/v5) strips it automatically; harmless either way.
if command -v docker >/dev/null 2>&1; then docker network create coolify >/dev/null 2>&1 || true; fi

cat <<'DONE'

==> Setup complete. Start the FULL stack (app + Postgres + data-engine + Redis + live seeders):

      docker compose --profile engine up --build

    App:    http://localhost:3000          (health: http://localhost:3000/api/health)
    Engine: http://localhost:5000/manifest  (should list the 14 discovered seeders)

    First build takes a few minutes (Next.js + Cesium). The globe fills in within ~1 min
    of the engine booting as each seeder's first fetch lands.
DONE
